name: selenium_web_test
on: push

jobs:
  web_test:
    runs-on: ubuntu-22.04
    env:
      NOTION_MAIL: ${{ secrets.NOTION_MAIL }}
      NOTION_PASS: ${{ secrets.NOTION_PASS }}
    steps:
      - name: Setup Geckodriver
        uses: browser-actions/setup-geckodriver@v0.0.0
        with:
          geckodriver-version: "0.33.0"
      - run: geckodriver --version
      - name: set env geckodriver path
        run: echo "gecko_path=`which geckodriver`" >> "$GITHUB_ENV"
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1.1.0
      - run: firefox --version
      - name: set env firefox path
        run: echo "firebinary=`which firefox`" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: get python version
        run: python -V
      - name: package installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: TEMP - test env path
        run: |
          echo "$HOME"
          echo "ls -a $HOME/.mozilla/firefox/"
          ls -a $HOME/.mozilla/firefox/
          touch $HOME/.mozilla/firefox/profiles.ini
          echo "fireprofile=$HOME/.mozilla/firefox/profiles.ini" >> "$GITHUB_ENV"
      - name: run test
        run: |
          pwd
          cd test && python test_replace_text_editor.py forward
          cat ../replace_parameters.py
          cd .. && python Notion_text_replace.py
          cd test && python test_replace_text_editor.py backward
          cat ../replace_parameters.py
          cd .. && python Notion_text_replace.py
        env:
          GECKODRIVER_PATH: ${{ env.gecko_path }}
          FIREFOX_BINARY_PATH: ${{ env.firebinary }}
          FIREFOX_PROFILE_PATH: ${{ env.fireprofile }}
